#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".seo-setup.local"   # captured values live here, not the real .env

SITE="https://getnctrnl.com"

banner "Nocturnal Design Studio — get found on Google & AI search"

# ── Stage 1 ─────────────────────────────────────────────────────────────
stage "Google Search Console — add the domain"
say "Search Console is the one thing that actually gets the site crawled fast."
say "We use a DNS 'Domain' property: it covers www, http/https and every path."
open_url "https://search.google.com/search-console/welcome"
step "Sign in with the Google account that should own the site's search data."
step "In the LEFT box titled 'Domain', type:   getnctrnl.com   then click Continue."
step "Google shows a TXT record value like:  google-site-verification=AbC123..."
step "Copy that whole value (including the google-site-verification= part)."
ask GSC_TXT_RECORD "Paste the TXT record value:"
write_env GSC_TXT_RECORD "$GSC_TXT_RECORD"
note "Leave this Search Console tab open — we come back to click Verify in Stage 3."

# ── Stage 2 ─────────────────────────────────────────────────────────────
stage "GoDaddy DNS — add the TXT record"
say "getnctrnl.com's DNS is at GoDaddy (nameservers ns57/ns58.domaincontrol.com)."
open_url "https://dcc.godaddy.com/control/portfolio/getnctrnl.com/settings?tab=dns"
step "Sign in to GoDaddy if asked. You should see the DNS records for getnctrnl.com."
step "Click 'Add New Record'."
step "Type: TXT"
step "Name / Host:  @        (means the root domain; some panels want it blank)"
say  "Value / TXT Value:  paste this —"
printf '\n      %s%s%s\n\n' "$BOLD" "${GSC_TXT_RECORD:-<the value from Stage 1>}" "$RESET"
step "TTL: leave default (1 hour / 3600)."
step "Save the record."
note "DNS can take a few minutes to propagate. If Verify fails first time, wait 10"
note "minutes and retry — it almost always works within the hour."
pause "Press Enter once the record is saved."

# ── Stage 3 ─────────────────────────────────────────────────────────────
stage "Search Console — verify + submit the sitemap"
say "Back on the Search Console tab from Stage 1."
step "Click 'Verify'. If it fails, wait ~10 min for DNS and click Verify again."
confirm "Did Search Console confirm ownership is verified?" \
  || warn "Give DNS more time, then re-open Search Console and Verify. You can keep going."
say ""
say "Now register the sitemap so Google discovers every page:"
open_url "https://search.google.com/search-console/sitemaps?resource_id=sc-domain%3Agetnctrnl.com"
step "In the 'Add a new sitemap' field, type:   sitemap.xml"
step "Click Submit. Status should become 'Success' within a day."
pause "Press Enter once the sitemap is submitted."

# ── Stage 4 ─────────────────────────────────────────────────────────────
stage "Search Console — request indexing for the key pages"
say "This pushes Google to crawl each page now instead of waiting."
open_url "https://search.google.com/search-console/inspect?resource_id=sc-domain%3Agetnctrnl.com"
say "For EACH url below: paste it in the top 'Inspect any URL' bar, press Enter,"
say "wait for the check, then click 'Request Indexing' and wait for the popup to finish."
step "$SITE/"
step "$SITE/work"
step "$SITE/renders"
step "$SITE/concepts"
step "$SITE/pricing"
step "$SITE/contact"
note "Google caps this at ~10/day — the 6 above are the priority set."
pause "Press Enter once you've requested indexing for all six."

# ── Stage 5 ─────────────────────────────────────────────────────────────
stage "Bing Webmaster Tools — import from Google"
say "Bing also feeds Copilot / ChatGPT search, so it's worth 2 minutes."
open_url "https://www.bing.com/webmasters/home"
step "Sign in (Microsoft account)."
step "On the start screen choose 'Import' under 'Import your sites from GSC'."
step "Click 'Import', authorise Google, pick getnctrnl.com, confirm."
note "Verification + the sitemap carry over automatically from Search Console."
pause "Press Enter once the import finishes."

# ── Stage 6 ─────────────────────────────────────────────────────────────
stage "Google Business Profile — create the studio listing"
say "A Business Profile is what powers the branded box on the right of a Google"
say "search for 'Nocturnal Design Studio'. Use the SAME Google account as Stage 1."
open_url "https://business.google.com/create"
step "Business name:   Nocturnal Design Studio"
step "Business category:   Design agency   (add 'Graphic designer' as a second one later)"
step "'Do you want to add a location customers can visit?'  ->  No."
step "Service area:  add  Mumbai  (plus 'India' / 'Worldwide' if you take remote work)."
step "Contact:  phone  +91 70454 21516   ·   website  $SITE"
step "Finish, then pick a verification method (phone or video is fastest; postcard = ~1 wk)."
warn "Verification is a separate Google process and can take days. That's normal."
pause "Press Enter once the profile is submitted for verification."

# ── Stage 7 ─────────────────────────────────────────────────────────────
stage "Link back from your social profiles"
say "The site's structured data lists these as official profiles. Google trusts"
say "that far more when the profiles link back to getnctrnl.com (two-way match)."
open_url "https://www.behance.net/abeermahad064c"
step "Behance: Edit Profile -> 'On the Web' / website field -> add  $SITE"
open_url "https://www.linkedin.com/in/abeermahadane44/"
step "LinkedIn: Edit intro -> Contact info -> Website -> add  $SITE  (label: Company)."
step "LinkedIn: also add 'Nocturnal Design Studio' as your current Experience/Company"
step "          with $SITE as its link."
open_url "https://www.instagram.com/designwithabeer/"
step "Instagram: Edit profile -> Links / Website -> add  $SITE"
step "Instagram: put 'Nocturnal Design Studio (NDS)' in the bio text too."
pause "Press Enter once all three link to the site."

finish
note "What happens next, roughly:"
note "  · 1-3 days  — Search Console 'Pages' report starts showing indexed URLs"
note "  · ~1 week   — 'getnctrnl' / 'nctrnl' searches should surface the site"
note "  · 2-6 weeks — 'nocturnal design studio' ranking settles as links are recrawled"
note "  · GBP verification runs on its own Google timeline"
note "Check progress at: https://search.google.com/search-console"
